### ISSUE TITLE
Possible to publish project's modules individually?

### ISSUE THREAD

**Issue by jamescway** [softprops/bintray-sbt#57]
It seems like bintray-sbt is publishing a whole project artifact that is empty.  My project consists of a bunch of sub projects (see [here](https://github.com/jamescway/zipkin)) .  
To package it I normally run `sbt package-dist` which creates a dist directory under each module. Is it possible to pull the jars out of each submodule with bintray-sbt?  Or do I need another plugin to do that intermediate step.  If so, is there something you recommend that works with bintray-sbt?

**Comment by softprops** [comment]
The problem is normally that sbt's publish task gets mixed in with the default settings for all projects. All projects includes your're typical aggregator project, a project that's only there for delegation and usually siting somewhere at the root ( `file(".")` ) of your build. You since you can override settings on a per project basis its common to disable publishing by overriding is definition ( `publish := {}` ) in that projects settings. 

Alternatively, a bunch of work was done in the [latest release](http://notes.implicit.ly/post/118407794254/bintray-sbt-0-3-0) to add support for sbt's newish autoPlugins feature which should give your build more control over which projects a plugin is enabled or disabled in
For more information on auto plugins see the [sbt docs](http://www.scala-sbt.org/0.13/docs/Plugins.html)

**Comment by jamescway** [comment]
@softprops Indeed overriding the publish causes the aggregator to not get published.

How would I individually publish the modules at this point?  
I have a setting per module:
```publishTo := Some(Resolver.file("file",  new File(Path.userHome.absolutePath + "/.ivy2/local")))```
It seems like it should be something pointing to Bintray?  Is this where bintray-sbt steps in?  I had tried the bintray URL  https://dl.bintray.com/jamescway/maven but got a 405 response.

**Comment by jamescway** [comment]
@softprops any thoughts? :smile:

**Comment by jamescway** [comment]
I upgraded to 0.3.0 and sbt seems to be publishing the individual modules to bintray.  One weird thing was that I had to manually create the module, which wasn't a big deal for me.
